FROM python:3.9

WORKDIR /app

COPY ./app/ /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

ENV MODEL_NAME=gpt3-turbo
ENV OPENAI_API_KEY=your-api-key

CMD streamlit runn app/app.py --server.port 8501 --server.enableCORS false
